module: 'bingo-gin'

app_env_mode: 'develop'
app_http_read_timeout: 120
app_http_write_timeout: 120
app_consolelog_file: 'console.log'
app_acesslog_file: 'access.log'

log:
  output_path: '/tmp/bingo-gin-console.log'
  open_stacktrace: false

http:
  develop:
    listen_port: ':8080'
  release:
    listen_port: ':80'

mysql:
  database: 'bingo'
  develop:
    port: '3306'
    host: '127.0.0.1'
    user: 'root'
    pwd: 'root'
  release:
    port: '3306'
    host: '127.0.0.1'
    user: 'root'
    pwd: 'root'